"""Partial identification under bounded regime-specific proxy calibration drift.

This module sits between the stable-calibration result (N3) and the
unconstrained-drift impossibility result (N4).

Let total performance and a proxy of one positive channel be

    W_i = F_i E_i,
    X_i = q_i F_i,

and define ``kappa = q_1 / q_0``. If calibration drift is bounded by

    kappa in [1-delta, 1+delta],  0 <= delta < 1,

then the two channel ratios are jointly constrained by

    rho_F = rho_X / kappa,
    rho_E = rho_E_hat * kappa,
    rho_F * rho_E = rho_W.

The marginal intervals each have multiplicative width
``(1+delta)/(1-delta)``, but they are not independent. On log-ratio coordinates
``(log rho_F, log rho_E)``, the sharp joint identified set is a line segment of
slope -1 on ``log rho_F + log rho_E = log rho_W``.

The functions below provide deterministic calculations and design diagnostics.
They do not estimate ``delta`` from data and do not turn an assumed bound into
empirical calibration evidence.
"""
from __future__ import annotations

from dataclasses import dataclass
from math import isclose, log
from typing import Literal


ChannelName = Literal["fecundity", "establishment"]
Direction = Literal["decrease", "increase", "ambiguous"]
DriftPlacement = Literal["multiplicative", "inverse"]


@dataclass(frozen=True)
class IdentifiedRatioInterval:
    """One marginal partially identified before/after channel ratio."""

    point_under_stability: float
    lower: float
    upper: float
    multiplicative_width: float
    direction_at_declared_bound: Direction
    breakdown_delta: float
    breakdown_censored_at_one: bool
    calibration_placement: DriftPlacement

    def contains(self, value: float, *, tolerance: float = 1e-12) -> bool:
        if value <= 0:
            return False
        return self.lower - tolerance <= value <= self.upper + tolerance

    @property
    def excludes_one(self) -> bool:
        return self.upper < 1.0 or self.lower > 1.0


@dataclass(frozen=True)
class JointLogIdentifiedSegment:
    """Sharp joint identified set in log-ratio coordinates.

    The endpoints correspond to the two admissible calibration-ratio endpoints.
    Every interior point is generated by one common kappa. The segment lies on
    ``log(rho_F) + log(rho_E) = log(net_ratio)`` and therefore has slope -1.
    """

    log_fecundity_at_kappa_lower: float
    log_establishment_at_kappa_lower: float
    log_fecundity_at_kappa_upper: float
    log_establishment_at_kappa_upper: float
    log_net_ratio: float
    slope: float = -1.0
    perfect_negative_dependence: bool = True

    def satisfies_net_constraint(self, *, tolerance: float = 1e-12) -> bool:
        return (
            isclose(
                self.log_fecundity_at_kappa_lower
                + self.log_establishment_at_kappa_lower,
                self.log_net_ratio,
                rel_tol=tolerance,
                abs_tol=tolerance,
            )
            and isclose(
                self.log_fecundity_at_kappa_upper
                + self.log_establishment_at_kappa_upper,
                self.log_net_ratio,
                rel_tol=tolerance,
                abs_tol=tolerance,
            )
        )


@dataclass(frozen=True)
class BoundedProxyDriftResult:
    """Sharp joint identified set for both channels under bounded calibration."""

    proxy_channel: ChannelName
    delta: float
    calibration_ratio_lower: float
    calibration_ratio_upper: float
    net_ratio: float
    proxy_ratio: float
    fecundity: IdentifiedRatioInterval
    establishment: IdentifiedRatioInterval
    joint_log_segment: JointLogIdentifiedSegment

    def interval_for(self, channel: ChannelName) -> IdentifiedRatioInterval:
        if channel == "fecundity":
            return self.fecundity
        if channel == "establishment":
            return self.establishment
        raise ValueError(f"unknown channel: {channel}")


@dataclass(frozen=True)
class BoundedDriftDesignRule:
    """Operational interpretation of one identified interval."""

    target_channel: ChannelName
    status: Literal["sign_identified", "partially_identified_sign_ambiguous"]
    report: str
    next_measurement: str


def _positive(value: float, name: str) -> float:
    result = float(value)
    if result <= 0:
        raise ValueError(f"{name} must be strictly positive")
    return result


def _validate_delta(delta: float) -> float:
    result = float(delta)
    if not 0.0 <= result < 1.0:
        raise ValueError("delta must satisfy 0 <= delta < 1")
    return result


def _direction(lower: float, upper: float, *, tolerance: float) -> Direction:
    if tolerance < 0:
        raise ValueError("tolerance must be non-negative")
    if upper < 1.0 - tolerance:
        return "decrease"
    if lower > 1.0 + tolerance:
        return "increase"
    return "ambiguous"


def breakdown_point(
    point_under_stability: float,
    *,
    calibration_placement: DriftPlacement = "multiplicative",
    tolerance: float = 1e-12,
) -> tuple[float, bool]:
    point = _positive(point_under_stability, "point_under_stability")
    if tolerance < 0:
        raise ValueError("tolerance must be non-negative")
    if isclose(point, 1.0, rel_tol=tolerance, abs_tol=tolerance):
        return 0.0, False

    if calibration_placement == "multiplicative":
        raw = 1.0 / point - 1.0 if point < 1.0 else 1.0 - 1.0 / point
    elif calibration_placement == "inverse":
        raw = 1.0 - point if point < 1.0 else point - 1.0
    else:
        raise ValueError(f"unknown calibration_placement: {calibration_placement}")

    raw = max(0.0, raw)
    censored = raw >= 1.0
    return min(raw, 1.0), censored


def identified_ratio_interval(
    point_under_stability: float,
    *,
    delta: float,
    calibration_placement: DriftPlacement = "multiplicative",
    tolerance: float = 1e-12,
) -> IdentifiedRatioInterval:
    point = _positive(point_under_stability, "point_under_stability")
    bound = _validate_delta(delta)

    if calibration_placement == "multiplicative":
        lower = point * (1.0 - bound)
        upper = point * (1.0 + bound)
    elif calibration_placement == "inverse":
        lower = point / (1.0 + bound)
        upper = point / (1.0 - bound)
    else:
        raise ValueError(f"unknown calibration_placement: {calibration_placement}")

    breakdown, censored = breakdown_point(
        point,
        calibration_placement=calibration_placement,
        tolerance=tolerance,
    )
    return IdentifiedRatioInterval(
        point_under_stability=point,
        lower=lower,
        upper=upper,
        multiplicative_width=upper / lower,
        direction_at_declared_bound=_direction(lower, upper, tolerance=tolerance),
        breakdown_delta=breakdown,
        breakdown_censored_at_one=censored,
        calibration_placement=calibration_placement,
    )


def _joint_log_segment(
    *,
    net_ratio: float,
    proxy_ratio: float,
    proxy_channel: ChannelName,
    kappa_lower: float,
    kappa_upper: float,
) -> JointLogIdentifiedSegment:
    if proxy_channel == "fecundity":
        f_lo_k = proxy_ratio / kappa_lower
        e_lo_k = (net_ratio / proxy_ratio) * kappa_lower
        f_hi_k = proxy_ratio / kappa_upper
        e_hi_k = (net_ratio / proxy_ratio) * kappa_upper
    elif proxy_channel == "establishment":
        e_lo_k = proxy_ratio / kappa_lower
        f_lo_k = (net_ratio / proxy_ratio) * kappa_lower
        e_hi_k = proxy_ratio / kappa_upper
        f_hi_k = (net_ratio / proxy_ratio) * kappa_upper
    else:
        raise ValueError(f"unknown proxy_channel: {proxy_channel}")

    return JointLogIdentifiedSegment(
        log_fecundity_at_kappa_lower=log(f_lo_k),
        log_establishment_at_kappa_lower=log(e_lo_k),
        log_fecundity_at_kappa_upper=log(f_hi_k),
        log_establishment_at_kappa_upper=log(e_hi_k),
        log_net_ratio=log(net_ratio),
    )


def identify_under_bounded_proxy_drift(
    *,
    net_ratio: float,
    proxy_ratio: float,
    delta: float,
    proxy_channel: ChannelName = "fecundity",
    tolerance: float = 1e-12,
) -> BoundedProxyDriftResult:
    rho_w = _positive(net_ratio, "net_ratio")
    rho_x = _positive(proxy_ratio, "proxy_ratio")
    bound = _validate_delta(delta)

    if proxy_channel == "fecundity":
        fecundity_point = rho_x
        establishment_point = rho_w / rho_x
        fecundity_placement: DriftPlacement = "inverse"
        establishment_placement: DriftPlacement = "multiplicative"
    elif proxy_channel == "establishment":
        establishment_point = rho_x
        fecundity_point = rho_w / rho_x
        establishment_placement = "inverse"
        fecundity_placement = "multiplicative"
    else:
        raise ValueError(f"unknown proxy_channel: {proxy_channel}")

    kappa_lower = 1.0 - bound
    kappa_upper = 1.0 + bound
    return BoundedProxyDriftResult(
        proxy_channel=proxy_channel,
        delta=bound,
        calibration_ratio_lower=kappa_lower,
        calibration_ratio_upper=kappa_upper,
        net_ratio=rho_w,
        proxy_ratio=rho_x,
        fecundity=identified_ratio_interval(
            fecundity_point,
            delta=bound,
            calibration_placement=fecundity_placement,
            tolerance=tolerance,
        ),
        establishment=identified_ratio_interval(
            establishment_point,
            delta=bound,
            calibration_placement=establishment_placement,
            tolerance=tolerance,
        ),
        joint_log_segment=_joint_log_segment(
            net_ratio=rho_w,
            proxy_ratio=rho_x,
            proxy_channel=proxy_channel,
            kappa_lower=kappa_lower,
            kappa_upper=kappa_upper,
        ),
    )


def design_rule_for_interval(
    interval: IdentifiedRatioInterval,
    *,
    target_channel: ChannelName,
) -> BoundedDriftDesignRule:
    if interval.excludes_one:
        direction = interval.direction_at_declared_bound
        return BoundedDriftDesignRule(
            target_channel=target_channel,
            status="sign_identified",
            report=(
                f"Report the {target_channel} ratio interval "
                f"[{interval.lower:.6g}, {interval.upper:.6g}], its "
                f"{direction} sign conclusion, and calibration-drift breakdown "
                f"delta*={interval.breakdown_delta:.6g}."
            ),
            next_measurement=(
                "A direct channel assay or tighter calibration remains useful for "
                "precision, but is not required to retain the sign conclusion under "
                "the declared drift bound."
            ),
        )

    return BoundedDriftDesignRule(
        target_channel=target_channel,
        status="partially_identified_sign_ambiguous",
        report=(
            f"Report the {target_channel} ratio interval "
            f"[{interval.lower:.6g}, {interval.upper:.6g}] and do not claim a "
            "directional change because the set includes one."
        ),
        next_measurement=(
            "Measure the target channel directly, estimate the proxy conversion in "
            "both regimes, or justify a tighter calibration-drift bound before making "
            "a sign claim."
        ),
    )
