"""Generality sweep: RACH-SEQ across a *family* of random confounded systems.

Where ``synthetic_demo`` shows the RACH workflow on one hand-built synthetic
system, this module makes the generality claim *distributional*: it generates
many random confounded mechanism systems — varying the number of switches, the
number of independent confounds, which switches are coupled, their magnitudes,
and the underlying truth — and runs the closed-loop RACH-SEQ algorithm on each.
It then reports the *distribution* of how many confounding edges RACH-SEQ
resolves within a fixed observation budget.

This answers the reviewer objection that a single worked example (or a single
synthetic instance) cannot establish generality: generality is shown here as a
sweep over a population of systems with an error bar, not as one anecdote.

Random system
-------------
K binary mechanism switches. ``n_confounds`` independent traits, each driven by
*exactly two* driver switches with distinct magnitude coefficients. The
admissible region is generated by accepting (s, θ) draws whose ordinal trend is
positive for every trait — so each trait's two drivers form a disjunction
("at least one ON"), i.e. a confounding edge that the ordinal data cannot
separate. The remaining switches are inert (no edges).

For each trait a *quantitative magnitude* observation is available: measuring
the trait's slope magnitude pins down which driver is active, cutting that
trait's confounding edge. RACH-SEQ selects observations greedily by expected
edge cuts and iterates until the confounding graph is empty or the budget runs
out. Because the true magnitude is set by a fixed truth state per system, the
realised resolution is well defined.

Usage
-----
    python -m causal_model.generality_sweep --figure outputs/mee/generality_sweep.png
    python -m causal_model.generality_sweep --n-systems 300 --seed 0
"""
from __future__ import annotations

import argparse
import random
import statistics
from dataclasses import dataclass, field

from causal_model.causal_admissibility import (
    CandidateObservation,
    CandidateOutcome,
    causal_resolvability,
)
from causal_model.mechanism_equivalence import mechanism_equivalence_structure
from causal_model.rach_seq import rach_seq


# Distinct, well-separated driver magnitude coefficients (so single-driver
# magnitudes and the both-on magnitude occupy non-overlapping bins under the
# θ ∈ [0.8, 1.2] scale and the measurement tolerance below).
_DRIVER_COEFFS = (0.30, 0.60)
_THETA_LO, _THETA_HI = 0.8, 1.2
_SLOPE_TOL = 0.05          # ordinal: trait slope must exceed this to count as a trend
_MAG_TOL = 0.07            # measurement half-tolerance on the quantitative magnitude


class _SW:
    """Minimal switch object (the inference layer only needs ``.name``)."""
    __slots__ = ("name",)

    def __init__(self, name: str):
        self.name = name


@dataclass
class SystemRecord:
    """RACH-SEQ outcome for one random system."""
    K: int
    n_confounds: int
    n_initial_edges: int
    n_resolved: int
    n_unresolved: int
    converged: bool
    steps_taken: int
    R0: float
    R_final: float

    @property
    def frac_resolved(self) -> float:
        if self.n_initial_edges == 0:
            return 1.0
        return self.n_resolved / self.n_initial_edges


@dataclass
class SweepResult:
    n_systems: int
    records: list[SystemRecord] = field(default_factory=list)

    # aggregate summaries (filled by _summarize)
    frac_converged: float = float("nan")
    mean_frac_resolved: float = float("nan")
    median_frac_resolved: float = float("nan")
    mean_R0: float = float("nan")
    mean_R_final: float = float("nan")
    mean_steps: float = float("nan")
    systems_with_edges: int = 0


# ---------------------------------------------------------------------------
# Random system construction
# ---------------------------------------------------------------------------

def _make_random_system(rng: random.Random, K: int, n_confounds: int):
    """Build one random confounded system.

    Returns
    -------
    (switches, drivers_per_trait, truth_driver_per_trait)
        switches: list[_SW]
        drivers_per_trait: list[(name_a, name_b)] — the two drivers of each trait
        truth_driver_per_trait: list[name] — the driver that is ON in the truth
    """
    names = [f"s{i}" for i in range(K)]
    switches = [_SW(n) for n in names]

    # Assign disjoint driver pairs to traits.
    pool = names[:]
    rng.shuffle(pool)
    drivers_per_trait: list[tuple[str, str]] = []
    for t in range(n_confounds):
        a, b = pool[2 * t], pool[2 * t + 1]
        drivers_per_trait.append((a, b))

    # Truth: exactly one driver ON per trait (which one is random).
    truth_driver = [rng.choice(pair) for pair in drivers_per_trait]
    return switches, drivers_per_trait, truth_driver


def _abc_accept(rng: random.Random, switches, drivers_per_trait, n_attempts: int):
    """Generate the admissible region: accept draws with a positive trend on
    every trait. Each accepted row carries the per-trait magnitude column
    ``trait{t}_mag`` and the boolean switch columns."""
    names = [sw.name for sw in switches]
    accepted: list[dict] = []
    for _ in range(n_attempts):
        s = {n: (rng.random() < 0.5) for n in names}
        theta = rng.uniform(_THETA_LO, _THETA_HI)
        mags: list[float] = []
        ok = True
        for (a, b) in drivers_per_trait:
            slope = theta * (_DRIVER_COEFFS[0] * int(s[a]) + _DRIVER_COEFFS[1] * int(s[b]))
            mags.append(slope)
            if slope <= _SLOPE_TOL:        # require a positive ordinal trend
                ok = False
                break
        if not ok:
            continue
        row = dict(s)
        row["theta"] = theta
        for t, m in enumerate(mags):
            row[f"trait{t}_mag"] = round(m, 4)
        accepted.append(row)
    return accepted


def _truth_magnitude(driver_name: str, pair: tuple[str, str]) -> float:
    """Magnitude (at θ=1) when only ``driver_name`` of ``pair`` is ON."""
    coeff = _DRIVER_COEFFS[0] if driver_name == pair[0] else _DRIVER_COEFFS[1]
    return coeff


def _candidates_for_system(drivers_per_trait, truth_driver):
    """One quantitative-magnitude observation per trait, whose single outcome is
    the system's true magnitude for that trait."""
    cands: list[CandidateObservation] = []
    for t, (pair, td) in enumerate(zip(drivers_per_trait, truth_driver)):
        true_mag = _truth_magnitude(td, pair)
        cands.append(CandidateObservation(
            name=f"measure_trait{t}_magnitude",
            description=f"Measure the quantitative magnitude of trait {t}.",
            target_switches=list(pair),
            rationale=f"The magnitude pins which of {pair} drives trait {t}.",
            pattern_type="absolute_summary",
            outcomes=[CandidateOutcome(
                name=f"trait{t}_mag_observed",
                description=f"Trait {t} magnitude measured ≈ {true_mag:.2f}.",
                prior_probability=1.0,
                # scale*2 is the effective tolerance in _row_matches_pattern,
                # so halve _MAG_TOL to make the effective half-width = _MAG_TOL.
                extra_pattern_rows=[{
                    "type": "absolute_summary",
                    "variable": "mag",
                    "population": f"trait{t}",
                    "observed_value": f"{true_mag:.6f}",
                    "scale": f"{_MAG_TOL / 2:.6f}",
                }],
            )],
        ))
    return cands


# ---------------------------------------------------------------------------
# Sweep
# ---------------------------------------------------------------------------

def run_generality_sweep(
    n_systems: int = 200,
    seed: int = 0,
    *,
    n_attempts: int = 1500,
    K_choices: tuple[int, ...] = (4, 5, 6),
    confound_choices: tuple[int, ...] = (1, 2),
    budget: int = 4,
    min_sub_size: int = 8,
) -> SweepResult:
    """Run RACH-SEQ on ``n_systems`` random confounded systems.

    Each system draws K from ``K_choices`` and the number of confounds from
    ``confound_choices`` (capped so 2·n_confounds ≤ K). The sweep records, per
    system, how many confounding edges RACH-SEQ resolved within ``budget``.
    """
    master = random.Random(seed)
    res = SweepResult(n_systems=n_systems)

    for i in range(n_systems):
        sys_rng = random.Random(master.randrange(1 << 30))
        K = sys_rng.choice(K_choices)
        max_conf = K // 2
        n_conf = min(sys_rng.choice(confound_choices), max_conf)

        switches, drivers, truth_driver = _make_random_system(sys_rng, K, n_conf)
        accepted = _abc_accept(sys_rng, switches, drivers, n_attempts)
        if len(accepted) < min_sub_size:
            continue   # degenerate draw; skip

        init_struct = mechanism_equivalence_structure(accepted, switches)
        R0 = causal_resolvability(accepted, switches)
        candidates = _candidates_for_system(drivers, truth_driver)

        seq = rach_seq(
            accepted, switches, candidates,
            budget=budget, min_sub_size=min_sub_size,
            seed=sys_rng.randrange(1 << 30),
        )

        res.records.append(SystemRecord(
            K=K,
            n_confounds=n_conf,
            n_initial_edges=len(init_struct.edges),
            n_resolved=len(seq.edges_resolved),
            n_unresolved=len(seq.edges_unresolved),
            converged=seq.converged,
            steps_taken=len(seq.observations_taken),
            R0=round(R0, 4),
            R_final=round(seq.steps[-1].R, 4),
        ))

    _summarize(res)
    return res


def _summarize(res: SweepResult) -> None:
    recs = res.records
    if not recs:
        return
    with_edges = [r for r in recs if r.n_initial_edges > 0]
    res.systems_with_edges = len(with_edges)
    base = with_edges or recs
    res.frac_converged = sum(1 for r in base if r.converged) / len(base)
    res.mean_frac_resolved = statistics.mean(r.frac_resolved for r in base)
    res.median_frac_resolved = statistics.median(r.frac_resolved for r in base)
    res.mean_R0 = statistics.mean(r.R0 for r in recs)
    res.mean_R_final = statistics.mean(r.R_final for r in recs)
    res.mean_steps = statistics.mean(r.steps_taken for r in base)


# ---------------------------------------------------------------------------
# Reporting
# ---------------------------------------------------------------------------

def print_report(res: SweepResult) -> None:
    print("=" * 68)
    print("RACH-SEQ generality sweep — random confounded systems")
    print("=" * 68)
    print(f"systems run            : {len(res.records)} / {res.n_systems}")
    print(f"systems with ≥1 edge   : {res.systems_with_edges}")
    if not res.records:
        print("no systems produced a usable admissible region.")
        return
    print(f"fully converged        : {res.frac_converged * 100:.1f}%  "
          f"(all confounding edges cut within budget)")
    print(f"edges resolved (mean)  : {res.mean_frac_resolved * 100:.1f}%  "
          f"(median {res.median_frac_resolved * 100:.1f}%)")
    print(f"resolvability R        : {res.mean_R0:.3f} → {res.mean_R_final:.3f}  "
          f"(mean over systems)")
    print(f"observations taken     : {res.mean_steps:.2f} (mean)")
    # Breakdown by number of confounds
    by_conf: dict[int, list[SystemRecord]] = {}
    for r in res.records:
        by_conf.setdefault(r.n_confounds, []).append(r)
    print("-" * 68)
    print("by number of confounds:")
    for nc in sorted(by_conf):
        grp = [r for r in by_conf[nc] if r.n_initial_edges > 0]
        if not grp:
            continue
        conv = sum(1 for r in grp if r.converged) / len(grp)
        fr = statistics.mean(r.frac_resolved for r in grp)
        print(f"   {nc} confound(s): n={len(grp):4d}  converged={conv*100:5.1f}%  "
              f"edges resolved={fr*100:5.1f}%")


def make_figure(res: SweepResult, path: str) -> str | None:
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        import numpy as np
    except Exception:
        print("matplotlib unavailable — skipping figure.")
        return None
    import os
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)

    recs = [r for r in res.records if r.n_initial_edges > 0]
    if not recs:
        print("no systems with confounding edges — skipping figure.")
        return None

    fig, axes = plt.subplots(1, 2, figsize=(9.5, 4.0))

    # Panel A: distribution of fraction of confounding edges resolved
    ax = axes[0]
    fr = [r.frac_resolved for r in recs]
    ax.hist(fr, bins=np.linspace(0, 1.0001, 12), color="#1f77b4",
            edgecolor="white")
    ax.axvline(res.mean_frac_resolved, color="#d62728", ls="--", lw=1.5,
               label=f"mean {res.mean_frac_resolved*100:.0f}%")
    ax.set_xlabel("fraction of confounding edges resolved")
    ax.set_ylabel("number of systems")
    ax.set_title(f"(A) Generality: edge resolution\nacross {len(recs)} random systems "
                 f"({res.frac_converged*100:.0f}% fully converged)")
    ax.legend(fontsize=8)

    # Panel B: resolvability R before vs after RACH-SEQ
    ax = axes[1]
    r0 = [r.R0 for r in recs]
    rf = [r.R_final for r in recs]
    lim = max(max(r0 + rf), 0.1) * 1.1
    ax.plot([0, lim], [0, lim], "k--", lw=1, label="1:1 (no gain)")
    # jitter for visibility
    jit = np.random.default_rng(0).normal(0, lim * 0.004, size=len(r0))
    ax.scatter(np.array(r0) + jit, np.array(rf) + jit, s=14, alpha=0.5,
               c="#2ca02c", zorder=3)
    ax.set_xlim(0, lim); ax.set_ylim(0, lim)
    ax.set_xlabel("R before (ordinal only)")
    ax.set_ylabel("R after RACH-SEQ")
    ax.set_title(f"(B) Resolvability gain\nmean R {res.mean_R0:.2f} → {res.mean_R_final:.2f}")
    ax.legend(fontsize=8)

    fig.tight_layout()
    fig.savefig(path, dpi=130)
    plt.close(fig)
    return path


def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="RACH-SEQ generality sweep over random confounded systems.")
    p.add_argument("--n-systems", type=int, default=200)
    p.add_argument("--n-attempts", type=int, default=1500)
    p.add_argument("--budget", type=int, default=4)
    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--figure", default="")
    return p


def main(argv: list[str] | None = None) -> int:
    args = _build_parser().parse_args(argv)
    res = run_generality_sweep(
        n_systems=args.n_systems, seed=args.seed,
        n_attempts=args.n_attempts, budget=args.budget,
    )
    print_report(res)
    if args.figure:
        out = make_figure(res, args.figure)
        if out:
            print(f"\nFigure written: {out}")
    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main())
